### ISSUE TITLE
Setting as_df=True in embedder.transoform causes an error

### ISSUE THREAD

**Issue by lukyanenkomax** [dkn22/embedder#1]
I tried to set as_`df=True` in fit_transform but it causes an error:
Traceback (most recent call last):
  File "emb_test.py", line 157, in <module>
    emb_data=embedder.fit_transform(data_encoded,y,as_df=True)
  File "/opt/conda/lib/python3.6/site-packages/embedder/classification.py", line 73, in fit_transform
    return self.transform(X, as_df=as_df)
  File "/opt/conda/lib/python3.6/site-packages/embedder/base.py", line 136, in transform
    names = [var + '_{}'.format(x) for x in range(emb_dim)
NameError: name 'emb_dim' is not defined
It seems like it is some kind of issue with list comprehensions.
This issue can be fixed by replacing lines 136 and 137 with 
`names = [var + '_{}'.format(x) for var, emb_dim in sizes for x in range(emb_dim)]`
Next error after performing this fix is:
Traceback (most recent call last):
  File "emb_test.py", line 157, in <module>
    emb_data=embedder.fit_transform(data_encoded,y,as_df=True)
  File "/opt/conda/lib/python3.6/site-packages/embedder/classification.py", line 73, in fit_transform
    return self.transform(X, as_df=as_df)
  File "/opt/conda/lib/python3.6/site-packages/embedder/base.py", line 140, in transform
    embedded = pd.DataFrame(embedded, columns=names)
NameError: name 'pd' is not defined
It can be fixed by adding `import pandas as pd` in the head of base.py

**Comment by dkn22** [comment]
@lukyanenkomax thanks for pointing this out! Would you like to submit a pull request?
